import json

datos={
"equipos":{
    "col":{
        "jugadores colombia":{
            10:{"Nombre":"James ",
                "Apellido":"Rodriguez",
                "Lugar de nacimiento":"Cúcuta",
                "Fecha de nacimiento":"12/07/1991",
                "Edad":"32",
                "Posicion": "Medio campo - Medio centro",
                "Altura":"1,81 m",
                "Pie":"Izquierdo",
                "Nacionalidad":"Colombia/España",
                "Club Actual":"Sao paulo Fc"
                  },
            4:{"Nombre":"Santiago",
                "Apellido":"Arias",
                "Lugar de nacimiento":"Medellín",
                "Fecha de nacimiento":"13/01/1992",
                "Edad":"31",
                "Posicion": "Defensa lateral derecho",
                "Altura":"1,77 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"FC cincinnati"
                  },
            18:{"Nombre":"Frank",
                "Apellido":"Fabra",
                "Lugar de nacimiento":"Nechí",
                "Fecha de nacimiento":"22/02/1991",
                "Edad":"32",
                "Posicion": "Defensa lateral izquierdo",
                "Altura":"1,74 m",
                "Pie":"Izquierdo",
                "Nacionalidad":"Colombia/Argentina",
                "Club Actual":"CA Boca Juniors"
                  },
            12:{"Nombre":"Camilo",
                "Apellido":"Vargas",
                "Lugar de nacimiento":"Bogotá",
                "Fecha de nacimiento":"09/03/1989",
                "Edad":"34",
                "Posicion": "Portero",
                "Altura":"1,85 m",
                "Pie":"Izquierdo",
                "Nacionalidad":"Colombia",
                "Club Actual":"Atlas Guadalajara"
                  },
            2:{"Nombre":"Carlos",
                "Apellido":"Cuesta",
                "Lugar de nacimiento":"Medellín",
                "Fecha de nacimiento":"09/03/1999",
                "Edad":"24",
                "Posicion": "Defensa central",
                "Altura":"1,79 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"KRC Genk"
                  },
            5:{"Nombre":"Wilmar",
                "Apellido":"Barrios",
                "Lugar de nacimiento":"Cartagena de indias",
                "Fecha de nacimiento":"16/10/1993",
                "Edad":"29",
                "Posicion": "Medio campo - pivote",
                "Altura":"1,78 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"Zenit de san petersburgo"
                  },
            15:{"Nombre":"Mateus",
                "Apellido":"Uribe",
                "Lugar de nacimiento":"Medellín",
                "Fecha de nacimiento":"21/03/1991",
                "Edad":"32",
                "Posicion": "Medio campo-Pivote",
                "Altura":"1,82 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"AL-Sadd SC"
                  },
            19:{"Nombre":"Rafael ",
                "Apellido":"Borre",
                "Lugar de nacimiento":"Barranquilla",
                "Fecha de nacimiento":"15/09/1995",
                "Edad":"28",
                "Posicion": "Delantero, Delantero centro",
                "Altura":"1,74 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"SV Werder Bremen"
                  },
            11:{"Nombre":"Jhon",
                "Apellido":"Arias",
                "Lugar de nacimiento":"Quibdó",
                "Fecha de nacimiento":"21/09/1997",
                "Edad":"26",
                "Posicion": "_Medio campo - Interior izquierdo",
                "Altura":"1,68 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"Fluminense Football Club"
                  },
            7:{"Nombre":"Luis",
                "Apellido":"Diaz",
                "Lugar de nacimiento":"Barrancas",
                "Fecha de nacimiento":"13/01/1997",
                "Edad":"26",
                "Posicion": "_Delantero extremo izquierdo",
                "Altura":"1,80 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"Liverpool FC"
                  },
            23:{"Nombre":"Davinson",
                "Apellido":"Sánchez",
                "Lugar de nacimiento":"Caloto",
                "Fecha de nacimiento":"12/09/1996",
                "Edad":"27",
                "Posicion": "Defensa, defensa central",
                "Altura":"1,87 m",
                "Pie":"Derecho",
                "Nacionalidad":"Colombia",
                "Club Actual":"Galatasaray"
                  }
        },
        "Seleccion colombiana":{
            "Nombre oficial":"Federación Colombiana de Fútbol",
            "Dirección":"Carrera 45 A No. 94-06/Bogotá",
            "Telefono":"+57 1 5185501",
            "Pagina web":"https://fcf.com.co/",
            "Fecha de fundacion":"12/10/1924"
        },
    },
    "auf":{
        "jugadores uruguay":{
            9:{"Nombre":"Darwin",
                "Apellido":"Nuñez",
                "Lugar de nacimiento":"Artigas",
                "Fecha de nacimiento":"24/06/1999",
                "Edad":"24",
                "Posicion": "Delantero, Delantero central",
                "Altura":"1,87 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay",
                                    "Club Actual":"Liverpool Fc"
                  },
            18:{"Nombre":"Brian",
                "Apellido":"Rodriguez",
                "Lugar de nacimiento":"Tranqueras",
                "Fecha de nacimiento":"20/05/2000",
                "Edad":"23",
                "Posicion": "Delantero extremo izquierdo",
                "Altura":"1,75 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay",
                "Club Actual":"CF América"
                  },
            7:{"Nombre":"Nicolas",
                "Apellido":"De La Cruz",
                "Lugar de nacimiento":"Montevideo",
                "Fecha de nacimiento":"01/06/1997",
                "Edad":"26",
                "Posicion": "Medio campo, Medio centro",
                "Altura":"1,77 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay/Argentina",
                "Club Actual": "CA River Lape"
                  },
            18:{"Nombre":"Brian",
                "Apellido":"Rodriguez",
                "Lugar de nacimiento":"Tranqueras",
                "Fecha de nacimiento":"20/05/2000",
                "Edad":"23",
                "Posicion": "Delantero extremo izquierdo",
                "Altura":"1,75 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay",
                "Club Actual":"CF América"
                  },
            11:{"Nombre":"Facundo",
                "Apellido":"Pellistri",
                "Lugar de nacimiento":"Montevideo",
                "Fecha de nacimiento":"20/12/2001",
                "Edad":"21",
                "Posicion": "DElantero extremo derecho",
                "Altura":"1,75 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay/España",
                "Club Actual":"Manchester United"
                  },
            15:{"Nombre":"Federico",
                "Apellido":"Valverde",
                "Lugar de nacimiento":"Montevideo",
                "Fecha de nacimiento":"22/07/1998",
                "Edad":"25",
                "Posicion": "Medio campo, Medio centro",
                "Altura":"1,82 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay/España",
                "Club Actual":"Real Madrid CF"
                  },
            18:{"Nombre":"Manuel",
                "Apellido":"Ugarte",
                "Lugar de nacimiento":"Montevideo",
                "Fecha de nacimiento":"11/04/2001",
                "Edad":"22",
                "Posicion": "Medio campo,Pivote",
                "Altura":"1,82 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay",
                "Club Actual":"París saint-Germain FC"
                  },
            22:{"Nombre":"Joaquín",
                "Apellido":"Piquerez",
                "Lugar de nacimiento":"Montevideo",
                "Fecha de nacimiento":"24/08/1998",
                "Edad":"25",
                "Posicion": "Defensa lateral izquierdo",
                "Altura":"1,84 m",
                "Pie":"Izquierdo",
                "Nacionalidad":"Uruguay/Italia",
                "Club Actual":"SE Palmeiras"
                  },
            2:{"Nombre":"Sebastian",
                "Apellido":"Caceres",
                "Lugar de nacimiento":"montevideo",
                "Fecha de nacimiento":"18/08/1999",
                "Edad":"24",
                "Posicion": "Defensa central",
                "Altura":"1,80 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay",
                "Club Actual":"CF America"
                  },
            4:{"Nombre":"Ronald",
                "Apellido":"Araujo",
                "Lugar de nacimiento":"Rivera",
                "Fecha de nacimiento":"07/03/1999",
                "Edad":"24",
                "Posicion": "Defensa, Defensa central",
                "Altura":"1,92 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay/España",
                "Club Actual":"FC Barcelona"
                  },
            8:{"Nombre":"Naitan",
                "Apellido":"Nandezz",
                "Lugar de nacimiento":"Punta del este",
                "Fecha de nacimiento":"28/12/1995",
                "Edad":"27",
                "Posicion": "Medio campo, Medio centro",
                "Altura":"1,72 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay/Italia",
                "Club Actual":"Cagliari"
                  },
            23:{"Nombre":"Santiago",
                "Apellido":"Mele",
                "Lugar de nacimiento":"Montevideo",
                "Fecha de nacimiento":"06/09/1997",
                "Edad":"26",
                "Posicion": "Portero",
                "Altura":"1,85 m",
                "Pie":"Derecho",
                "Nacionalidad":"Uruguay/Italia",
                "Club Actual":"Junior de barranquilla" }

                  },
    "Seleccion Uruguaya":{
            "Nombre oficial":"Asociación Uruguaya de Fútbol",
            "Dirección":"Guayabo 1531 Montevideo/Uruguay",
            "Telefono":"+59 82 4004814",
            "Pagina web":"https://fcf.com.co/",
            "Fundacion":"	auf.org.uy",
        }



    }

}
}
print ("Juagadores Colombia")
print(json.dumps(datos ["equipos"] ["col"], sort_keys=False, indent=4))
print ("Juagadores Uruguay")
print(json.dumps(datos ["equipos"] ["auf"], sort_keys=True, indent=4))